version: "3"
services: 
  app:
    build: .
    image: node:11
    command: npm run dev
    ports:
      - "8000:8000"
    links:
      - db
    working_dir: /usr/src/app
    environment:
      SEQ_DB: rpgprojeto
      SEQ_USER: postgres
      SEQ_PW: 123456
      PORT: 8000
      DATABASE_URL: postgres://postgres:123456@db:5432/rpgprojeto
    volumes:
      - ./:/usr/src/app  
  db:
    image: postgres
    ports:
    - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456