version: "3"
services: 
  app:
    build: .
    depends_on: 
      - db
    environment: 
      SEQ_DB: rpgprojeto
      SEQ_USER: postgres
      SEQ_PW: 123456
      DATABASE_URL: postgres://postgres:123456@db:5432/rpgprojeto
      NODE_ENV: development
      PORT: 3000
    ports: 
      - "3000:3000"
    command: npm run dev
    volumes: 
      - .:/src/
      - ./src/node_modules
  db:
    image: postgres
    ports: 
      - "35432:5432"
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: rpgprojeto
    volumes: 
      - ./pgdata:/var/lib/postgrsql/data


