version: "3"
services: 
  app:
    build: .
    image: gabrielpittacosta/rpg:1.1.11
    command: npm run dev
    ports:
      - "8000:8000"
    depends_on:
      - db
    working_dir: /usr/src/app
    environment:
      SEQ_DB: rpgprojeto
      SEQ_USER: postgres
      SEQ_PW: 123456
      PORT: 8000
      DATABASE_URL: postgres://postgres:123456@host.docker.internal:5432/rpgprojeto
    volumes:
      - ./:/usr/src/app  
  db:
    image: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgres/data/db-files
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456