apiVersion: v1
kind: Pod
metadata:
  name: postgres
spec:
  containers:
    - name: container-postgres
      image: postgres
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "123456"
        - name: POSTGRES_DB
          value: "rpgprojeto"