apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-api-rpg
spec:
  serviceName: postgres
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: container-postgres-api-rpg
        image: postgres:9.6.2
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: "123456"
        - name: POSTGRES_DB
          value: rpgprojeto
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432          
          name: rpg
        volumeMounts:
        - name: volume-postgres-api-rpg
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: volume-postgres-api-rpg
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 3Gi