apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: aplicacao-deployment
spec:
  template:
    metadata:
      labels:
        name: aplicacao-pod
    spec:
      containers:
        - name: container-app-rpg
          image: gabrielpittacosta/rpg:1.1.12
          ports:
            - containerPort: 8000